name:                c-compiler-hs
version:             1.0.0
github:              "t-sasaki915/c-compiler-hs"
license:             "MIT"
author:              "T Sasaki"
maintainer:          "netst915@gmail.com"
copyright:           "2023 T Sasaki"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/c-compiler-hs#readme>

dependencies:
- base >= 4.7 && < 5
- extra
- regex-compat

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  c-compiler-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-compiler-hs

tests:
  c-compiler-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-compiler-hs
    - HUnit
